### ISSUE TITLE
run server wrong

### ISSUE THREAD

**Issue by weizhenzhao** [tripzero/python-wss#1]
Hi Dear 
I met an error when call the websocket server in the js
the server side is using your wss wssserver
with the code like following
import wss
import asyncio

loop = asyncio.get_event_loop()

server =  wss.Server(port=9001, useSsl=True, sslCert="server.crt",
					 sslKey="server.key")

def onTextMessage(server, msg, client):
	print("got message from client:", msg)

def onBinaryMessage(server, msg, client):
	print("got binary message")

server.onMessage = onTextMessage
server.onBinaryMessage = onBinaryMessage

@asyncio.coroutine
def sendData():
	while True:
		try:
			print("trying to broadcast...")
			server.broadcast("{'hello' : 'world' }")
		except:
			exc_type, exc_value, exc_traceback = sys.exc_info()
			traceback.print_tb(exc_traceback, limit=1, file=sys.stdout)
			traceback.print_exception(exc_type, exc_value, exc_traceback,
                          limit=2, file=sys.stdout)

		yield from asyncio.sleep(30)

def stop_loop():
	print("loop stops")
	#loop.stop()

#loop.call_later(0.1, stop_loop)
loop.create_task(sendData())

server.start()
loop.run_forever()

the js part is like the following

`

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>
</head>
<body>

    <div>
        <video id="live" width="320" height="240" autoplay style="display: inline;"></video>
        <canvas width="320" id="canvas" height="240" style="display: inline;"></canvas>
    </div>

    var video = $("#live").get()[0];
    var canvas = $("#canvas");
    var ctx = canvas.get()[0].getContext('2d');
    window.WebSocket=window.WebSocket || window.MozWebSocket;

    var ws = new WebSocket("wss://192.168.1.103:9001");
    ws.onopen = function () {
        console.log("Openened connection to websocket");
    }

    // 收到WebSocket服务器数据
    ws.onmessage = function(e) {
        // e.data contains received string.
        console.log("onmessage: " + e.data);
    };

    // 关闭WebSocket连接
    ws.onclose = function() {
        console.log("onclose");
    };

    // WebSocket连接出现错误
    ws.onerror = function(e) {
        console.log(e)
      };

    ws.send("hello");

    navigator.webkitGetUserMedia({video:true, audio:true},
          function(stream) {
            video.src = window.webkitURL.createObjectURL(stream);
          },
            function(err) {
                console.log("Unable to get video stream!")
            }
      );

     var dataURI = function dataURIToBlob(dataurl){
        var arr = dataurl.split(',');
        var mime = arr[0].match(/:(.*?);/)[1];
        var bstr = atob(arr[1]);
        var n = bstr.length;
        var u8arr = new Uint8Array(n);
        while(n--){
            u8arr[n] = bstr.charCodeAt(n);
        }
        return new Blob([u8arr], {type:mime});
    }

        timer = setInterval(
            function () {
                ctx.drawImage(video, 0, 0, 320, 240);
                var data = canvas.get()[0].toDataURL('image/jpeg', 1.0);
                newblob = dataURI(data);
                //ws.send(newblob);
            }, 250);
</script>

</body>
</html>

`

and the error in server side looks like the following:
`Exception in callback _BatchedTimer._notify_bucket(4444000)()
handle: <TimerHandle when=4444.0000368440005 _BatchedTimer._notify_bucket(4444000)()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/site-packages/txaio/_common.py", line 111, in _notify_bucket
    notify_one_chunk(calls, self._chunk_size, max(0.0, delay_ms))
  File "/usr/local/lib/python3.5/site-packages/txaio/_common.py", line 105, in notify_one_chunk
    raise RuntimeError(msg)
RuntimeError: Error(s) processing call_later bucket:
not implemented`

**Comment by tripzero** [comment]
First problem is your message callback signature are wrong.  You should be using server.setTextHandler (see https://github.com/tripzero/python-wss/blob/master/wss/wssserver.py#L97).  The README should be fixed

There appears to be a couple issues in the server code however with ssl which is causing your error.  I have a fix I will push shortly.

**Comment by tripzero** [comment]
Does the latest commit fix the issue for you?

**Comment by weizhenzhao** [comment]
Hi tripzero

Sorry I've change to another wss framework called autobahn
and I've finished my demo with it
here's my demo's link [https://github.com/weizhenzhao/Face_Recognise](url)

Thank you for you help
WeiZhen

**Comment by tripzero** [comment]
python-wss uses autobahn in the background but tries to make a simpler
interface.  Glad you got it working nontheless.  Cool project.
